name: "gbraad's Dotfiles `app` Action"
description: 'Wrapper for app command execution on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  appname:
    description: 'The application name'
    required: true
    default: ''
  action:
    description: 'Command to execute (instal, remove, run, etc. otherwise possible default)'
    required: false
    default: 'install'
  context:
    description: 'Optional packager or OS to use (fedora, dnf, brew, etc.)'
    required: false
    default: ''
  args:
    description: 'Optional arguments (--background, --evaluate, etc.)'
    required: false
    default: ''
  as_user:
    description: 'User to run the commands as (optional)'
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Execute app command
      uses: gbraad-actions/zsh-action@main
      with:
        as_user: ${{ inputs.as_user }}
        run: |
          # Check if app function exists
          if ! type app >/dev/null 2>&1; then
            echo "Error: app function is not defined. Please make sure to run install first"
            exit 1
          fi
          
          # Execute app command
          app ${{ inputs.appname }} ${{ inputs.action }} ${{ inputs.context }} ${{ inputs.args }}
